import type { Metadata } from "next";
import type React from "react";
import { Roboto_Condensed } from "next/font/google";
import { CartProvider } from "@/context/CartContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.variable} font-sans antialiased bg-white text-zinc-900 overflow-x-hidden`}
      >
        <CartProvider>
          <div className="flex min-h-screen flex-col">
            <header className="bg-white">
              <div className="mx-auto w-full max-w-6xl px-6 py-4 lg:px-10 lg:py-5">
                <Header />
              </div>
            </header>
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
