import type { Metadata } from "next";
import type React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-zinc-900 overflow-x-hidden`}
      >
        <div className="flex min-h-screen flex-col">
        <header className="bg-white/70 backdrop-blur-md">
  <div className="mx-auto w-full max-w-6xl px-6 py-4 lg:px-10 lg:py-5">
    <Header />
  </div>
</header>

          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
